### PR TITLE
PR for #91 - Add missing Conditionals.php & Conditionals.rb

### PR DESCRIPTION
**Pull request by chess-equality**
#91

### CODE REVIEW

**Comment by BFergerson** [comment]
Opened some PRs to deal with missing roles:
- https://github.com/bblfsh/php-driver/pull/56
- https://github.com/bblfsh/ruby-driver/pull/53

Will hold this PR open till those are released.

**Comment by BFergerson** [comment]
@chess-equality, please resolve the merge conflicts.

**Comment by chess-equality** [comment]
@BFergerson It's resolved and merged.

**Comment by BFergerson** [comment]
Added todos to track PRs. It doesn't seem babelfish updates its drivers all too often. Will use the current way until they release new versions.

**Pull request merged**
